<?php session_start();
    include("./func/bc-spadmin-config.php");
    if($connection){
    	header("Location: /bc-spadmin");
        exit();
    }
    if(isset($_POST["setup"])){
    	$host = trim(strip_tags($_POST["host"]));
    	$dbname = trim(strip_tags($_POST["dbname"]));
    	$user = trim(strip_tags($_POST["user"]));
    	$pass = trim(strip_tags($_POST["pass"]));
    	
        if(!empty($host) && !empty($dbname) && !empty($user)){
            // Test connection first
            mysqli_report(MYSQLI_REPORT_OFF);
            $test_conn = @mysqli_connect($host, $user, $pass, $dbname);
            
            if ($test_conn) {
                mysqli_close($test_conn);
                $db_json_text = '<?php
/**
 * DGV6.90 — Secure Database Credentials
 * Automatically generated by installer
 */
function _bc_db_config_safe(): array {
    return [
        \'server\'  => \''.$host.'\',
        \'user\'    => \''.$user.'\',
        \'pass\'    => \''.$pass.'\',
        \'dbname\'  => \''.$dbname.'\',
        \'app_env\' => \'production\',
    ];
}
$db_json_decode = _bc_db_config_safe();
$db_json_dtls   = $db_json_decode;
$db_json_encode = json_encode($db_json_decode);
?>';
                file_put_contents("./func/db-json.php", $db_json_text);
                $_SESSION["product_purchase_response"] = "Database Configuration Initialized Successfully!";
            } else {
                $_SESSION["product_purchase_response"] = "Connection Failed: " . mysqli_connect_error();
            }
    	}else{
            $_SESSION["product_purchase_response"] = "Error: Please fill all required fields.";
    	}
		
        if (isset($_SESSION["product_purchase_response"]) && str_contains($_SESSION["product_purchase_response"], "Successfully")) {
            header("Location: /saSetup.php");
        } else {
            header("Location: ".$_SERVER["REQUEST_URI"]);
        }
        exit();
    }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Database Setup | DGV6.90 AI Edition</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="assets-2/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets-2/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <style>
        :root {
            --primary: #6366f1;
            --primary-dark: #4f46e5;
            --glass: rgba(255, 255, 255, 0.7);
            --glass-border: rgba(255, 255, 255, 0.4);
        }

        body {
            background: radial-gradient(circle at top left, #f5f3ff, #ede9fe);
            color: #1e293b;
            font-family: 'Plus Jakarta Sans', sans-serif;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
            overflow-x: hidden;
        }

        body::before {
            content: "";
            position: absolute;
            width: 300px;
            height: 300px;
            background: var(--primary);
            filter: blur(120px);
            opacity: 0.15;
            top: -100px;
            right: -100px;
            z-index: -1;
        }

        body::after {
            content: "";
            position: absolute;
            width: 400px;
            height: 400px;
            background: #818cf8;
            filter: blur(140px);
            opacity: 0.1;
            bottom: -150px;
            left: -150px;
            z-index: -1;
        }

        .setup-card {
            max-width: 480px;
            width: 100%;
            padding: 2.5rem;
            border-radius: 24px;
            background: var(--glass);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            border: 1px solid var(--glass-border);
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.08);
            position: relative;
            z-index: 1;
        }

        .icon-box {
            width: 64px;
            height: 64px;
            background: linear-gradient(135deg, var(--primary), #818cf8);
            color: white;
            border-radius: 18px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 28px;
            margin: 0 auto 1.5rem;
            box-shadow: 0 10px 20px -5px rgba(99, 102, 241, 0.4);
        }

        .form-label {
            font-size: 0.8rem;
            font-weight: 700;
            color: #64748b;
            margin-bottom: 0.5rem;
            letter-spacing: 0.025em;
        }

        .input-group-text {
            background: transparent;
            border-right: none;
            border-radius: 12px 0 0 12px;
            color: #94a3b8;
            padding-left: 1rem;
        }

        .form-control {
            border-radius: 12px;
            padding: 0.75rem 1rem;
            background: rgba(255, 255, 255, 0.5);
            border: 1px solid rgba(203, 213, 225, 0.5);
            font-weight: 500;
            transition: all 0.2s ease;
        }

        .form-control:focus {
            background: #fff;
            border-color: var(--primary);
            box-shadow: 0 0 0 4px rgba(99, 102, 241, 0.1);
        }

        .btn-setup {
            background: linear-gradient(135deg, var(--primary), var(--primary-dark));
            color: white;
            border: none;
            border-radius: 14px;
            padding: 1rem;
            font-weight: 700;
            letter-spacing: 0.05em;
            transition: all 0.3s ease;
            box-shadow: 0 8px 16px -4px rgba(99, 102, 241, 0.3);
        }

        .btn-setup:hover {
            transform: translateY(-2px);
            box-shadow: 0 12px 20px -4px rgba(99, 102, 241, 0.4);
            filter: brightness(1.1);
        }

        .alert-modern {
            border-radius: 14px;
            border: none;
            background: rgba(99, 102, 241, 0.1);
            color: var(--primary-dark);
            font-weight: 600;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .footer-brand {
            margin-top: 2rem;
            font-size: 0.75rem;
            color: #94a3b8;
        }

        .brand-accent {
            color: var(--primary);
            font-weight: 700;
        }
    </style>
</head>
<body>

    <div class="setup-card">
        <div class="text-center">
            <div class="icon-box">
                <i class="bi bi-hdd-network-fill"></i>
            </div>
            <h3 class="fw-bold mb-1">Database Setup</h3>
            <p class="text-muted mb-4 small px-4">Connect your database to initialize the DGV6.90 Platform</p>
        </div>

        <?php if(isset($_SESSION["product_purchase_response"])): ?>
            <div class="alert alert-modern fade show py-3 px-4 mb-4" role="alert">
                <i class="bi bi-stars"></i>
                <div class="small"><?php echo $_SESSION["product_purchase_response"]; unset($_SESSION["product_purchase_response"]); ?></div>
            </div>
        <?php endif; ?>

        <form method="post" action="">
            <div class="mb-3">
                <label class="form-label text-uppercase">Host Address</label>
                <div class="input-group">
                    <span class="input-group-text border-end-0"><i class="bi bi-globe"></i></span>
                    <input name="host" type="text" value="<?php echo $mySqlServer ?? 'localhost'; ?>" placeholder="e.g. localhost" class="form-control border-start-0" required>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label text-uppercase">Database Name</label>
                <div class="input-group">
                    <span class="input-group-text border-end-0"><i class="bi bi-database"></i></span>
                    <input name="dbname" type="text" value="<?php echo $mySqlDBName ?? ''; ?>" placeholder="Enter database name" class="form-control border-start-0" required>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label text-uppercase">Database User</label>
                <div class="input-group">
                    <span class="input-group-text border-end-0"><i class="bi bi-person-circle"></i></span>
                    <input name="user" type="text" value="<?php echo $mySqlUser ?? ''; ?>" placeholder="Enter username" class="form-control border-start-0" required>
                </div>
            </div>
            <div class="mb-4">
                <label class="form-label text-uppercase">Database Password</label>
                <div class="input-group">
                    <span class="input-group-text border-end-0"><i class="bi bi-shield-lock"></i></span>
                    <input name="pass" type="password" placeholder="••••••••" class="form-control border-start-0">
                </div>
            </div>
            <button name="setup" type="submit" class="btn btn-setup w-100 mb-3">
                INITIALIZE PLATFORM
            </button>
            <div class="text-center footer-brand">
                <p class="mb-0">Securely Powered by <span class="brand-accent">Philmore Codes</span></p>
            </div>
        </form>
    </div>

    <script src="assets-2/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script>
        // Auto-dismiss alert
        setTimeout(function() {
            var alert = document.querySelector('.alert');
            if (alert) {
                alert.style.transition = 'opacity 0.5s ease';
                alert.style.opacity = '0';
                setTimeout(() => alert.remove(), 500);
            }
        }, 5000);
    </script>
</body>
</html>